CREATE TABLE IF NOT EXISTS `product` (
    `id` int NOT NULL AUTO_INCREMENT,
    `shop_id` int NOT NULL DEFAULT 0 COMMENT '商家id',
    `product_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商品编号',
    `cover_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '商品封面图',
    `gallery_images` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '商品轮播图（JSON格式）',
    `stock` int NOT NULL DEFAULT 0 COMMENT '库存',
    `name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商品名称',
    `specification` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '规格',
    `unit` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '单位',
    `price` int NOT NULL DEFAULT 0 COMMENT '原价，单位分',
    `open_discount` tinyint NOT NULL DEFAULT 0 COMMENT '是否开启折扣（0:否, 1:是）',
    `discount_num` decimal(10, 1) NOT NULL DEFAULT 0.0 COMMENT '折扣',
    `open_discount_time` tinyint NOT NULL DEFAULT 0 COMMENT '是否开启折扣倒计时（0:否, 1:是）',
    `discount_time` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '折扣倒计时',
    `amount` int NOT NULL DEFAULT 0 COMMENT '售价，单位分',
    `sort` int NULL DEFAULT 0 COMMENT '排序',
    `status` tinyint NOT NULL DEFAULT 2 COMMENT '上架状态（1:上架, 2:下架，3:定时上架）',
    `scheduled_time` datetime(0) NULL DEFAULT NULL COMMENT '定时上架时间',
    `is_virtual` tinyint NOT NULL DEFAULT 0 COMMENT '是否是虚拟商品（0:否, 1:是）',
    `time_limit` int NOT NULL DEFAULT 0 COMMENT '有效期（天），虚拟商品才有',
    `detail` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '商品详情（富文本）',
    `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '备注',
    `sale_num` int NOT NULL DEFAULT 0 COMMENT '销量',
    `create_time` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    `delete_time` datetime(0) NULL DEFAULT NULL COMMENT '删除时间',
    primary key (id)
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '商品管理表' ROW_FORMAT = DYNAMIC;
