CREATE TABLE IF NOT EXISTS `product_order` (
    `id` int NOT NULL AUTO_INCREMENT COMMENT '订单id',
    `order_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '订单编号',
    `user_id` int NOT NULL DEFAULT 0 COMMENT '下单用户id',
    `phone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '下单手机号',
    `nick_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '下单用户昵称',
    `equipment_id` int UNSIGNED NOT NULL DEFAULT 0 COMMENT '设备id',
    `serial_number` VARCHAR(50) NOT NULL DEFAULT '' COMMENT '设备编号',
    `shop_id` int NOT NULL DEFAULT 0 COMMENT '商家id',
    `shop_name` varchar(255) COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商家名称',
    `product_id` int NOT NULL DEFAULT 0 COMMENT '商品id',
    `product_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商品编号',
    `cover_image` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '商品封面图',
    `product_name` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '商品名称',
    `specification` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '规格',
    `unit` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '单位',
    `is_virtual` tinyint NOT NULL DEFAULT 0 COMMENT '是否是虚拟商品（0:否, 1:是）',
    `deadline` timestamp(0) NULL DEFAULT NULL COMMENT '有效截止时间，虚拟商品才有',
    `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '' COMMENT '备注',
    `price` int NOT NULL DEFAULT 0 COMMENT '单价（分）',
    `num` int NOT NULL DEFAULT 0 COMMENT '数量',
    `amount` int NOT NULL DEFAULT 0 COMMENT '支付总金额（分）',
    `status` tinyint NOT NULL DEFAULT 0 COMMENT '订单状态: 0待支付、1待使用(虚拟商品)、2待发货(非虚拟商品)、3已发货(非虚拟商品)、4已完成、5退款中、6已退款、7已过期(虚拟商品)、8已取消',
    `refund_amount` int NOT NULL DEFAULT 0 COMMENT '退款金额(分)',
    `refund_time` timestamp(0) NULL DEFAULT NULL COMMENT '退款时间',
    `refund_remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '退款说明',
    `express_company_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '快递公司名称',
    `express_company_code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '快递公司标识码',
    `express_no` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT '' COMMENT '快递单号',
    `express_status` tinyint NOT NULL DEFAULT -2 COMMENT '物流状态：-2--无，-1--待发货，0--在途，1--揽件，2--疑难，3--签收，4--退签，5--派件，6--退回，10--待清关，11--清关中，12--已清关，13--清关异常，14--收件人拒签',
    `create_time` datetime(0) NOT NULL COMMENT '创建时间',
    `update_time` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0) ON UPDATE CURRENT_TIMESTAMP(0) COMMENT '更新时间',
    primary key (id),
    INDEX `idx_user_status`(`user_id`, `status`) USING BTREE
)ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT '商品订单管理表' ROW_FORMAT = DYNAMIC;
