CREATE TABLE IF NOT EXISTS `reconciliation_transaction_flow` (
                                                                 `id` int UNSIGNED NOT NULL AUTO_INCREMENT,
                                                                 `shop_id` int NOT NULL DEFAULT 0 COMMENT '店铺ID',
                                                                 `bill_date` date NOT NULL COMMENT '归属日期',
                                                                 `transaction_time` datetime NOT NULL COMMENT '交易时间',
                                                                 `order_no` varchar(50) NOT NULL COMMENT '订单号',
                                                                 `merchant_order_no` varchar(100) DEFAULT '' COMMENT '外部单号',
                                                                 `order_id` bigint NOT NULL DEFAULT 0 COMMENT '业务订单ID',
                                                                 `order_type` tinyint NOT NULL DEFAULT 0 COMMENT '订单类型(1商城,2租赁等)',
                                                                 `type` tinyint NOT NULL DEFAULT 1 COMMENT '类型: 1收款, 2退款',
                                                                 `amount` bigint NOT NULL DEFAULT 0 COMMENT '交易金额(分)',
                                                                 `service_fee` bigint NOT NULL DEFAULT 0 COMMENT '手续费(分)',
                                                                 `product_name` varchar(255) DEFAULT '' COMMENT '商品名称',
                                                                 `total_quantity` int DEFAULT 0 COMMENT '总数量',
                                                                 `user_id` bigint DEFAULT 0 COMMENT '下单用户ID',
                                                                 `order_user` varchar(100) DEFAULT '' COMMENT '下单人姓名',
                                                                 `remark` text COMMENT '备注',
                                                                 `orderno` varchar(100) DEFAULT '' COMMENT '易宝订单号',
                                                                 `origin_merchant_order_no` varchar(100) DEFAULT '' COMMENT '原收款订单商户号',
                                                                 `origin_orderno` varchar(100) DEFAULT '' COMMENT '原收款订单易宝号',
                                                                 `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                                                 PRIMARY KEY (`id`),
                                                                 KEY `idx_bill_shop` (`bill_date`, `shop_id`),
                                                                 KEY `idx_order_no` (`order_no`),
                                                                 KEY `idx_order_id` (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='交易流水记录表';